name: release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+"
    paths-ignore:
      - ".github/workflows/**"

env:
  OCIREPO: lfedge/eve-rust

jobs:
  build_and_push:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0
      - name: Get rust version
        id: rust_version
        run: |
          RUST_VERSION=$(awk  -F= '/ARG RUST_VERSION/ {print $2}' Dockerfile)
          # make sure we got a rust version
          if [ -z "$RUST_VERSION" ]; then
            echo "Failed to get RUST_VERSION"
            exit 1
          fi
          # strip off any potential eve-specific extensions to the tag
          TAG="${{ github.ref_name }}"
          TAG="${TAG%%-*}"
          if [ "$TAG" != "$RUST_VERSION" ]; then
            echo "Tag $TAG does not match RUST_VERSION $RUST_VERSION"
            exit 1
          fi
          echo "IMAGE_TAG=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
      - name: Login to Docker Hub
        if: ${{ github.event.repository.full_name }} == 'lf-edge/eve-rust'
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121  # v4.1.0
        with:
          username: ${{ secrets.RELEASE_DOCKERHUB_ACCOUNT }}
          password: ${{ secrets.RELEASE_DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a  # v4.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd  # v4.0.0
      - uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294  # v7.0.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.OCIREPO }}:${{ steps.rust_version.outputs.IMAGE_TAG }}
            ${{ env.OCIREPO }}:latest
